# Deploy do postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  namespace: postgrecd
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.1
          env:
          - name: POSTGRES_PASSWORD
            value: Passw0rd2024!
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_DB
            value: admin
          ports:
            - name: dpostgre
              containerPort: 5432
